ARG LINKERD_AWAIT_VERSION=v0.1.2
FROM olix0r/linkerd-await:v0.1.1 as await

FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y openssh-server iperf && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/
RUN echo 'root:test' | chpasswd
RUN mkdir /var/run/sshd
# see https://docs.docker.com/engine/examples/running_ssh_service/
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22

COPY --from=await /linkerd-await /usr/bin/linkerd-await

ENV PATH="/usr/bin:${PATH}"
CMD bash -c 'service ssh restart && iperf -s -p 5001'
