ARG LINKERD_AWAIT_VERSION=v0.1.2

FROM fortio/fortio as build

FROM olix0r/linkerd-await:v0.1.1 as await
FROM ubuntu:latest
COPY --from=build /usr/bin/fortio /usr/bin/fortio
COPY --from=await /linkerd-await /usr/bin/linkerd-await
