ARG LINKERD_AWAIT_VERSION=v0.1.2

FROM fortio/fortio
RUN curl -vsLO https://github.com/olix0r/linkerd-await/releases/download/release/${LINKERD_AWAIT_VERSION}/linkerd-await
# ... install myapp ..
ENTRYPOINT ["/linkerd-await", "--"]
CMD ["fortio"]
