name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/shellcheck.yml
      - '**/*.sh'
      - justfile

jobs:
  sh-lint:
    timeout-minutes: 5
    runs-on: ${{ vars.LINKERD2_PROXY_RUNNER || 'ubuntu-24.04' }}
    steps:
      - uses: linkerd/dev/actions/setup-tools@v50
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: just sh-lint
